version: "3.9"

x-airflow-image: &airflow_image apache/airflow:2.9.2

services:
  postgres:
    image: postgres:15
    container_name: stock_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  adminer:
    image: adminer:4
    container_name: stock_adminer
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  airflow-init:
    image: *airflow_image
    container_name: airflow_init
    entrypoint: /bin/bash
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      _PIP_ADDITIONAL_REQUIREMENTS: "requests psycopg2-binary"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./app:/opt/airflow/app
      - ./logs:/opt/airflow/logs
    command: -c "airflow db migrate && \
      airflow users create --username ${AIRFLOW_USERNAME} --password ${AIRFLOW_PASSWORD} \
      --firstname Admin --lastname User --role Admin --email ${AIRFLOW_EMAIL} || true"

  airflow-webserver:
    image: *airflow_image
    container_name: airflow_web
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      _PIP_ADDITIONAL_REQUIREMENTS: "requests psycopg2-binary"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./app:/opt/airflow/app
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: *airflow_image
    container_name: airflow_sched
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      _PIP_ADDITIONAL_REQUIREMENTS: "requests psycopg2-binary"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./app:/opt/airflow/app
      - ./logs:/opt/airflow/logs
    command: scheduler

volumes:
  pgdata: